version: "3"

services:
    ipfsnode:
        image: ipfs/go-ipfs:latest
        volumes:
            - /data/ipfs:/data/ipfs
            - ./ipfsnode/config.ours:/data/ipfs/config:ro
        ports:
            - 4001:4001
        command: daemon --migrate=true

    nginx:
        image: nginx:1.15.1-alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
        ports:
            - "80:80"
            - "5001:5001"
